### ISSUE TITLE
Srcsets

### ISSUE THREAD

**Issue by alexwadd** [Heydon/inclusive-design-checklist#10]
Not sure if you have mentioned 'using srcsets over css for different mobile desktop images'. Apologies if you have.

**Comment by Heydon** [comment]
No, I haven't! Ideas for phrasing?

**Comment by stevepiron** [comment]
Maybe a bit long, but here's a suggestion:
> Use srcset to allow the browser to choose the best image depending on the characteristics of the device

**Comment by Heydon** [comment]
Implemented as "Use `srcset` to tailor images to devices and reduce bandwidth costs"
