### ISSUE TITLE
"Use relative units (em, rem, and ch), especially for font metrics"

### ISSUE THREAD

**Issue by o-t-w** [Heydon/inclusive-design-checklist#7]
Why?

**Comment by BNewing** [comment]
One reason is that using relative units means user preferences can be accepted. For example, a user might go into their browser settings/preferences and changed their default font-size to " very large":

![image](https://user-images.githubusercontent.com/16868713/32737035-e41dd022-c890-11e7-82e2-f166ffc16f34.png)

If you've used px, nothing will change. But if you've used relative units properly, this will be respected and the font size will scale up.

https://www.smashingmagazine.com/ does this well! :)

**Comment by Heydon** [comment]
@BNewing Spot on. Not everyone full-page zooms.

**Comment by tedw** [comment]
@BNewing Exactly! I don't think this is well known. I was just discussing this in the comments of this post about text sizing and zooming:
https://alastairc.ac/2017/11/is-text-sizing-dead/comment-page-1/#comment-205685

**Comment by rjbultitude** [comment]
I strongly recommend reading this article by (the well respected accessibility expert) Alistair Campbell: https://alastairc.ac/2017/11/is-text-sizing-dead/ before including any information about relative units. 
In it he argues that pixels are perfectly acceptable as a unit as all current browsers and assistive technologies support scaling via zoom. 

Excellent project BTW :]

**Comment by o-t-w** [comment]
Great link @rjbultitude 
Pixels are a lot easier to reason about.

**Comment by Heydon** [comment]
@rjbultitude Just because browsers support full-page zoom doesn't mean all users use it. Browsers also support changing default `font-size` via settings. 

Inclusive design is being flexible so that users can make their own choices. One reason a user might adjust the default `font-size` in settings is that it propagates automatically across all web pages that support it. No need to adjust zoom per page.

**Comment by rjbultitude** [comment]
Hi @Heydon 
I take your point, and just to be clear, I want all digital interfaces to be as inclusive as possible and was only recommending that Alistair's POV be considered. 
It might be worth noting that page zoom is a global browser setting (in Chrome for example) that will also propagate across all pages.

**Comment by rjbultitude** [comment]
It would be really helpful if anyone has any data about this topic. Evidence on the number or types of users that set the font size in browsers prefs would be really useful. Thanks

**Comment by Heydon** [comment]
@rjbultitude I would too, but I'm not sure why it is needed. The ability to adjust base font-size exists, and designing responsive interfaces is just so much easier when not using `px` based dimensions in any case.

**Comment by Heydon** [comment]
@rjbultitude Thanks for the info about zoom level being saved in Chrome. However, it only seems to be saved per page, not as a global.

**Comment by rjbultitude** [comment]
It's working globally in for me @Heydon , but some sites honour it and some don't depending on how the styles are configured.

**Comment by rikschennink** [comment]
This is great advice for component development as well.

Using a font-size in REM at the root of your component and EMs for its subtree elements makes it easy for others to change the font-size of the entire component by only changing the root element font-size. If you use PX for this, well, then no-go.

I only use PX if I want pixel perfect (pixel snapping?) rendering of decorative elements. With (R)EMs browsers sometimes tend to render half pixels or handle X axis EMs differently than Y axis EMs.
