### ISSUE TITLE
Rename the project to be less inclusive.

### ISSUE THREAD

**Issue by Julian-O** [Heydon/inclusive-design-checklist#9]
I know it is ironic, but the name of the checklist implies that it is about *all* design, where you are really just  talking about web-site (and perhaps app) design, and excluding everything else. For example, compare the scope of this list to *[The Design of Everyday Things](https://en.wikipedia.org/wiki/The_Design_of_Everyday_Things)*.

That limited scope should be reflected in the title.

**Comment by Heydon** [comment]
@Julian-O Good point! I will amend.

**Comment by miriambe** [comment]
Hi, Heydon. I applaud your project! I agree with Julian-O and yourself, in thinking it wise to clearly state what parts of "design" and "inclusive design" the list covers. For this purpose, I propose naming it: "Web Accessibility: Expert Inspection Checklist for Code, Content & UI Design" or similar. All the best!

**Comment by stevepiron** [comment]
Agreed. Just forked this for the company I work for and split the list into departments (design, dev, content), which makes the list a lot less intimidating :)

**Comment by jensgro** [comment]
The separation into multiple lists is a good idea. A very good example is [the checklist from Voxmedia](http://accessibility.voxmedia.com/). It narrows the tasks down for every "department". That's great for everyone working on a project.

**Comment by Heydon** [comment]
I have shared my thoughts on dividing up the list in https://github.com/Heydon/inclusive-design-checklist/issues/1. But to reiterate, different organizations have different departments and responsibilities. Some don't organize into departments. Hence, I'm not likely to create arbitrary categories.
